[project]
name = "helia-rt"
version = "0.2.2"
description = "Development tooling for the heliaRT microcontroller runtime."
authors = [
    {name = "Ambiq AI", email = "support.aitg@ambiq.com"},
]
readme = "README.md"

requires-python = ">=3.11,<3.13"

dependencies = ["ruff>=0.7.2"]


[dependency-groups]
dev = [
]

[tool.ruff]
line-length = 80
indent-width = 2
target-version = "py310"
extend-exclude = [
  "ci",
  "tensorflow/lite/python",
  "tensorflow/lite/tools",
  "third_party",
  "*.ipynb",
]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "B006",
  "B007",
  "B020",
]
ignore = [
  "E501",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
