/* Copyright 2026 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Generated by gen_float_data_movement.py using ai-edge-litert 2.2.0.
// see AmbiqAI/helia-rt#280
#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_FLOAT_DATA_MOVEMENT_GOLDENS_H_
#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_FLOAT_DATA_MOVEMENT_GOLDENS_H_
#include <cstdint>
namespace {
constexpr uint32_t kSplitGolden[] = {
    0x3f00f778, 0x3f011667, 0x3f013556, 0x3f01b112, 0x3f01d001, 0x3f01eef0,
    0x3f015445, 0x3f017334, 0x3f019223, 0x3f020ddf, 0x3f022cce, 0x3f024bbd};
constexpr uint32_t kPackGolden[] = {
    0x3f00f778, 0x3f011667, 0x3f013556, 0x3f015445, 0x3f017334, 0x3f019223,
    0x3f026aac, 0x3f02899b, 0x3f02a88a, 0x3f02c779, 0x3f02e668, 0x3f030557,
    0x3f01b112, 0x3f01d001, 0x3f01eef0, 0x3f020ddf, 0x3f022cce, 0x3f024bbd,
    0x3f032446, 0x3f034335, 0x3f036224, 0x3f038113, 0x3f03a002, 0x3f03bef1};
constexpr uint32_t kUnpackGolden[] = {
    0x3f00f778, 0x3f011667, 0x3f013556, 0x3f01b112, 0x3f01d001, 0x3f01eef0,
    0x3f015445, 0x3f017334, 0x3f019223, 0x3f020ddf, 0x3f022cce, 0x3f024bbd};
constexpr uint32_t kUnpackHalfGolden[] = {0x0008, 0x0009, 0x000a, 0x000e,
                                          0x000f, 0x0010, 0x000b, 0x000c,
                                          0x000d, 0x0011, 0x0012, 0x0013};
constexpr uint32_t kFillGolden[] = {
    0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778,
    0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778, 0x3f00f778};
constexpr uint32_t kFillHalfGolden[] = {0x0008, 0x0008, 0x0008, 0x0008,
                                        0x0008, 0x0008, 0x0008, 0x0008,
                                        0x0008, 0x0008, 0x0008, 0x0008};
}  // namespace
#endif
