# Copyright 2026 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Generate exact FP32 goldens with ai-edge-litert's reference interpreter.

Requires ai-edge-litert==2.2.0, flatbuffers, numpy and clang-format. Writes the adjacent header.
Attempts FP16 too and reports interpreter limitations; FP16 storage coverage in
float_data_movement_test.cc uses exhaustive independent bit references.
"""

from pathlib import Path
import subprocess

import flatbuffers
import numpy as np
from ai_edge_litert import schema_py_generated as schema
from ai_edge_litert.interpreter import Interpreter, OpResolverType


def evaluate(op, half=False):
  """Execute one explicitly shaped builtin with finite, nonuniform inputs."""
  model = schema.ModelT()
  model.version = 3
  model.buffers = [schema.BufferT()]
  graph = schema.SubGraphT()
  graph.tensors = []
  inputs = []
  tensor_type = schema.TensorType.FLOAT16 if half else schema.TensorType.FLOAT32

  def tensor(shape, kind=tensor_type, constant=None):
    value = schema.TensorT()
    value.shape = np.array(shape, dtype=np.int32)
    value.type = kind
    value.buffer = 0
    if constant is not None:
      buffer = schema.BufferT()
      buffer.data = np.frombuffer(constant.tobytes(), dtype=np.uint8)
      value.buffer = len(model.buffers)
      model.buffers.append(buffer)
    graph.tensors.append(value)
    return len(graph.tensors) - 1

  operator = schema.OperatorT()
  options = getattr(schema, op.title() + 'OptionsT')()
  if op == 'SPLIT':
    inputs.append(tensor([], schema.TensorType.INT32, np.array(-2, np.int32)))
    inputs.append(tensor([2, 2, 3]))
    outputs = [tensor([2, 1, 3]), tensor([2, 1, 3])]
    options.numSplits = 2
  elif op == 'UNPACK':
    inputs.append(tensor([2, 2, 3]))
    outputs = [tensor([2, 3]), tensor([2, 3])]
    options.axis = -2
    options.num = 2
  elif op == 'PACK':
    inputs = [tensor([2, 2, 3]), tensor([2, 2, 3])]
    outputs = [tensor([2, 2, 2, 3])]
    options.axis = -3
    options.valuesCount = 2
  else:
    inputs.append(tensor([3], schema.TensorType.INT32, np.array([2, 2, 3], np.int32)))
    inputs.append(tensor([]))
    outputs = [tensor([2, 2, 3])]
  graph.inputs = [i for i in inputs if graph.tensors[i].buffer == 0]
  graph.outputs = outputs
  operator.inputs = inputs
  operator.outputs = outputs
  operator.builtinOptionsType = getattr(schema.BuiltinOptions, op.title() + 'Options')
  operator.builtinOptions = options
  graph.operators = [operator]
  code = schema.OperatorCodeT()
  code.builtinCode = getattr(schema.BuiltinOperator, op)
  code.deprecatedBuiltinCode = min(code.builtinCode, 127)
  code.version = 1
  model.operatorCodes = [code]
  model.subgraphs = [graph]
  builder = flatbuffers.Builder(1024)
  builder.Finish(model.Pack(builder), file_identifier=b'TFL3')
  interpreter = Interpreter(model_content=bytes(builder.Output()),
                            experimental_op_resolver_type=OpResolverType.BUILTIN_REF)
  interpreter.allocate_tensors()
  offset = 8
  for item in interpreter.get_input_details():
    count = int(np.prod(item['shape']))
    bits = np.array([0x3f000000 + i * 7919 for i in range(offset, offset + count)], np.uint32)
    values = (np.arange(offset, offset + count, dtype=np.uint16).view(np.float16)
              if half else bits.view(np.float32)).reshape(item['shape'])
    interpreter.set_tensor(item['index'], values)
    offset += count
  interpreter.invoke()
  return np.concatenate([interpreter.get_tensor(i).reshape(-1) for i in outputs])


def main():
  lines = ['// Generated by gen_float_data_movement.py using ai-edge-litert 2.2.0.',
           '// see AmbiqAI/helia-rt#280',
           '#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_FLOAT_DATA_MOVEMENT_GOLDENS_H_',
           '#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_FLOAT_DATA_MOVEMENT_GOLDENS_H_',
           '#include <cstdint>', 'namespace {']
  for op in ('SPLIT', 'PACK', 'UNPACK', 'FILL'):
    values = evaluate(op).view(np.uint32)
    lines.append(f'constexpr uint32_t k{op.title()}Golden[] = {{')
    lines.append(', '.join(f'0x{int(value):08x}' for value in values) + '};')
    try:
      half_values = evaluate(op, half=True).view(np.uint16)
      lines.append(f'constexpr uint32_t k{op.title()}HalfGolden[] = {{')
      lines.append(', '.join(f'0x{int(value):04x}' for value in half_values) + '};')
      print(f'{op}: FP16 interpreter supported')
    except (RuntimeError, ValueError) as error:
      print(f'{op}: FP16 interpreter unsupported: {error}')
  lines.extend(['}  // namespace', '#endif', ''])
  output = Path(__file__).with_name('float_data_movement_goldens.h')
  license_text = Path(__file__).with_name('float_data_movement_test.cc').read_text().split('*/', 1)[0] + '*/\n\n'
  output.write_text(license_text + '\n'.join(lines))
  subprocess.run(['clang-format', '-i', str(output)], check=True)


if __name__ == '__main__':
  main()
