# Copyright 2026 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Generate single-op FP16 SQRT/RSQRT LiteRT model fixtures.

Requires ai-edge-litert==2.2.0 and flatbuffers. Finite expected bits use the
independent AmbiqAI/helia-core-tester#129 contract: binary64 evaluation followed
by one FP16 rounding. Special-bit fixtures are declared in the C++ test.
"""

from importlib.metadata import version
import math
from pathlib import Path
import struct

import flatbuffers
from ai_edge_litert import schema_py_generated as schema


INPUT_BITS = (
    0x0001,
    0x03FF,
    0x0400,
    0x3400,
    0x3C00,
    0x4000,
    0x4400,
    0x4800,
    0x5000,
)
SCALAR_INPUT_BITS = (0x4400,)


def fp16_reference(bits, reciprocal):
  """Evaluate positive finite FP16 bits using the tester #129 oracle rule."""
  value = struct.unpack('<e', struct.pack('<H', bits))[0]
  result = 1.0 / math.sqrt(value) if reciprocal else math.sqrt(value)
  return struct.unpack('<H', struct.pack('<e', result))[0]


def make_model(builtin_code, shape):
  model = schema.ModelT()
  model.version = 3
  model.buffers = [schema.BufferT()]

  graph = schema.SubGraphT()
  input_tensor = schema.TensorT()
  input_tensor.shape = shape
  input_tensor.type = schema.TensorType.FLOAT16
  input_tensor.buffer = 0
  output_tensor = schema.TensorT()
  output_tensor.shape = shape
  output_tensor.type = schema.TensorType.FLOAT16
  output_tensor.buffer = 0
  graph.tensors = [input_tensor, output_tensor]
  graph.inputs = [0]
  graph.outputs = [1]

  operator = schema.OperatorT()
  operator.opcodeIndex = 0
  operator.inputs = [0]
  operator.outputs = [1]
  operator.builtinOptionsType = schema.BuiltinOptions.NONE
  graph.operators = [operator]

  code = schema.OperatorCodeT()
  code.builtinCode = builtin_code
  code.deprecatedBuiltinCode = min(builtin_code, 127)
  code.version = 1
  model.operatorCodes = [code]
  model.subgraphs = [graph]

  builder = flatbuffers.Builder(1024)
  builder.Finish(model.Pack(builder), file_identifier=b'TFL3')
  return bytes(builder.Output())


def emit_bytes(name, values):
  lines = [f'constexpr unsigned char {name}[] = {{']
  for offset in range(0, len(values), 12):
    chunk = values[offset:offset + 12]
    lines.append('    ' + ', '.join(f'0x{value:02x}' for value in chunk) + ',')
  lines.append('};')
  return lines


def emit_words(name, values):
  lines = [f'constexpr uint16_t {name}[] = {{']
  for offset in range(0, len(values), 9):
    chunk = values[offset:offset + 9]
    lines.append('    ' + ', '.join(f'0x{value:04x}' for value in chunk) + ',')
  lines.append('};')
  return lines


def main():
  oracle_version = version('ai-edge-litert')
  if oracle_version != '2.2.0':
    raise RuntimeError(f'Expected ai-edge-litert 2.2.0, got {oracle_version}')

  sqrt_model = make_model(schema.BuiltinOperator.SQRT, [len(INPUT_BITS)])
  rsqrt_model = make_model(schema.BuiltinOperator.RSQRT, [len(INPUT_BITS)])
  sqrt_scalar_model = make_model(schema.BuiltinOperator.SQRT, [])
  rsqrt_scalar_model = make_model(schema.BuiltinOperator.RSQRT, [])
  sqrt_expected = [fp16_reference(bits, False) for bits in INPUT_BITS]
  rsqrt_expected = [fp16_reference(bits, True) for bits in INPUT_BITS]
  sqrt_scalar_expected = [fp16_reference(bits, False) for bits in SCALAR_INPUT_BITS]
  rsqrt_scalar_expected = [fp16_reference(bits, True) for bits in SCALAR_INPUT_BITS]

  lines = [
      '// Generated by gen_sqrt_rsqrt_fp16_models.py using ai-edge-litert 2.2.0.',
      '// Expected bits follow AmbiqAI/helia-core-tester#129.',
      '#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SQRT_RSQRT_FP16_MODELS_H_',
      '#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SQRT_RSQRT_FP16_MODELS_H_',
      '',
      '#include <cstdint>',
      '',
      'namespace {',
      '',
  ]
  lines += emit_bytes('kSqrtF16ModelData', sqrt_model)
  lines += ['', f'constexpr unsigned int kSqrtF16ModelDataSize = {len(sqrt_model)};', '']
  lines += emit_bytes('kRsqrtF16ModelData', rsqrt_model)
  lines += ['', f'constexpr unsigned int kRsqrtF16ModelDataSize = {len(rsqrt_model)};', '']
  lines += emit_bytes('kSqrtF16ScalarModelData', sqrt_scalar_model)
  lines += [
      '',
      f'constexpr unsigned int kSqrtF16ScalarModelDataSize = {len(sqrt_scalar_model)};',
      '',
  ]
  lines += emit_bytes('kRsqrtF16ScalarModelData', rsqrt_scalar_model)
  lines += [
      '',
      f'constexpr unsigned int kRsqrtF16ScalarModelDataSize = {len(rsqrt_scalar_model)};',
      '',
  ]
  lines += emit_words('kSqrtRsqrtModelInputBits', INPUT_BITS)
  lines += ['']
  lines += emit_words('kSqrtRsqrtScalarModelInputBits', SCALAR_INPUT_BITS)
  lines += ['']
  lines += emit_words('kSqrtF16ModelExpectedBits', sqrt_expected)
  lines += ['']
  lines += emit_words('kRsqrtF16ModelExpectedBits', rsqrt_expected)
  lines += ['']
  lines += emit_words('kSqrtF16ScalarModelExpectedBits', sqrt_scalar_expected)
  lines += ['']
  lines += emit_words('kRsqrtF16ScalarModelExpectedBits', rsqrt_scalar_expected)
  lines += [
      '',
      '}  // namespace',
      '',
      '#endif  // TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SQRT_RSQRT_FP16_MODELS_H_',
      '',
  ]

  license_end = Path(__file__).with_name('split_v_float_goldens.h').read_text().split('*/', 1)[0]
  output = Path(__file__).with_name('sqrt_rsqrt_fp16_models.h')
  output.write_text(license_end + '*/\n\n' + '\n'.join(lines))


if __name__ == '__main__':
  main()
