# Copyright 2026 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Generate SPLIT_V output bits/shapes with ai-edge-litert==2.2.0.

Requires flatbuffers, numpy and clang-format. Writes the adjacent header and
prints executed oracle results, including unsupported FLOAT16 cases.
"""

from importlib.metadata import version
import json
from pathlib import Path
import subprocess

import flatbuffers
import numpy as np
from ai_edge_litert import schema_py_generated as schema
from ai_edge_litert.interpreter import Interpreter, OpResolverType


CASES = (
    ('Inferred', [2, 5, 3], [1, -1, 2]),
    ('MixedZero', [2, 5, 3], [0, 2, 0, 3, 0]),
    ('TotalEmpty', [2, 5, 0], [1, -1, 2]),
)


def evaluate(shape, sizes, kind):
  """Return output shapes and storage bits from a reference SPLIT_V model."""
  model = schema.ModelT()
  model.version = 3
  model.buffers = [schema.BufferT()]
  graph = schema.SubGraphT()
  graph.tensors = []

  def tensor(dims, dtype, constant=None):
    value = schema.TensorT()
    value.shape = np.array(dims, dtype=np.int32)
    value.type = dtype
    value.buffer = 0
    if constant is not None:
      buffer = schema.BufferT()
      buffer.data = np.frombuffer(constant.tobytes(), dtype=np.uint8)
      value.buffer = len(model.buffers)
      model.buffers.append(buffer)
    graph.tensors.append(value)
    return len(graph.tensors) - 1

  dtype = getattr(schema.TensorType, kind)
  data = tensor(shape, dtype)
  splits = tensor([len(sizes)], schema.TensorType.INT32,
                  np.array(sizes, np.int32))
  axis = tensor([], schema.TensorType.INT32, np.array(-2, np.int32))
  # Output metadata is inferred by LiteRT, independently of the adapter.
  outputs = [tensor([], dtype) for _ in sizes]
  operator = schema.OperatorT()
  operator.inputs = [data, splits, axis]
  operator.outputs = outputs
  operator.builtinOptionsType = schema.BuiltinOptions.SplitVOptions
  operator.builtinOptions = schema.SplitVOptionsT()
  operator.builtinOptions.numSplits = len(sizes)
  graph.inputs = [data]
  graph.outputs = outputs
  graph.operators = [operator]
  code = schema.OperatorCodeT()
  code.builtinCode = schema.BuiltinOperator.SPLIT_V
  code.deprecatedBuiltinCode = min(code.builtinCode, 127)
  code.version = 1
  model.operatorCodes = [code]
  model.subgraphs = [graph]
  builder = flatbuffers.Builder(1024)
  builder.Finish(model.Pack(builder), file_identifier=b'TFL3')
  interpreter = Interpreter(model_content=bytes(builder.Output()),
                            experimental_op_resolver_type=OpResolverType.BUILTIN_REF)
  interpreter.allocate_tensors()
  count = int(np.prod(shape))
  if kind == 'FLOAT32':
    values = np.array([0x3f000000 + (8 + i) * 7919 for i in range(count)],
                      np.uint32).view(np.float32)
  elif kind == 'INT32':
    values = np.array([(i - 15) * 7919 for i in range(count)], np.int32)
  else:
    values = np.arange(8, 8 + count, dtype=np.uint16).view(np.float16)
  interpreter.set_tensor(data, values.reshape(shape))
  interpreter.invoke()
  actual = [interpreter.get_tensor(index) for index in outputs]
  bit_type = np.uint16 if kind == 'FLOAT16' else np.uint32
  return ([list(value.shape) for value in actual],
          [value.reshape(-1).view(bit_type).tolist() for value in actual])


def main():
  oracle_version = version('ai-edge-litert')
  if oracle_version != '2.2.0':
    raise RuntimeError(f'Expected ai-edge-litert 2.2.0, got {oracle_version}')
  print(f'ai-edge-litert {oracle_version}; BUILTIN_REF')
  lines = ['// Generated by gen_split_v_float.py using ai-edge-litert 2.2.0.',
           '#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SPLIT_V_FLOAT_GOLDENS_H_',
           '#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SPLIT_V_FLOAT_GOLDENS_H_',
           '#include <cstdint>', 'namespace {']
  for name, shape, sizes in CASES:
    for kind, suffix in (('FLOAT32', 'Float'), ('INT32', 'Int32'),
                         ('FLOAT16', 'Half')):
      try:
        shapes, values = evaluate(shape, sizes, kind)
      except (RuntimeError, ValueError) as error:
        if kind != 'FLOAT16':
          raise
        print(f'{name} {kind}: UNSUPPORTED: {error}')
        continue
      print(json.dumps({'case': name, 'dtype': kind, 'input_shape': shape,
                        'axis': -2, 'sizes': sizes, 'output_shapes': shapes,
                        'output_bits': values}))
      prefix = f'kSplitV{name}{suffix}'
      lines.append(f'constexpr int {prefix}Shapes[][3] = {{')
      lines.append(', '.join('{' + ', '.join(map(str, dims)) + '}'
                             for dims in shapes) + '};')
      lines.append(f'constexpr int {prefix}Counts[] = {{' +
                   ', '.join(str(len(value)) for value in values) + '};')
      bits = [bit for value in values for bit in value]
      width = 4 if kind == 'FLOAT16' else 8
      ctype = 'uint16_t' if kind == 'FLOAT16' else 'uint32_t'
      lines.append(f'constexpr {ctype} {prefix}Golden[] = {{')
      lines.append(', '.join(f'0x{bit:0{width}x}' for bit in bits or [0]) + '};')
  lines.extend(['}  // namespace', '#endif', ''])
  output = Path(__file__).with_name('split_v_float_goldens.h')
  license_text = Path(__file__).with_name('float_data_movement_goldens.h').read_text().split('*/', 1)[0] + '*/\n\n'
  output.write_text(license_text + '\n'.join(lines))
  subprocess.run(['clang-format', '-i', str(output)], check=True)


if __name__ == '__main__':
  main()
