/* Copyright 2026 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Generated by gen_model_hard_swish_depthwise.py. The goldens
// come from the TFLite reference interpreter; do not hand-edit.

#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_MODEL_HARD_SWISH_DEPTHWISE_DATA_H_
#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_MODEL_HARD_SWISH_DEPTHWISE_DATA_H_

#include <cstdint>

extern const unsigned char kHardSwishS8ModelData[];
extern const unsigned int kHardSwishS8ModelDataSize;
extern const int8_t kHardSwishS8Input[];
constexpr unsigned int kHardSwishS8InputSize = 32;
extern const int8_t kHardSwishS8Golden[];
constexpr unsigned int kHardSwishS8GoldenSize = 32;

extern const unsigned char kDepthwiseF32ModelData[];
extern const unsigned int kDepthwiseF32ModelDataSize;
extern const float kDepthwiseF32Input[];
constexpr unsigned int kDepthwiseF32InputSize = 256;
extern const float kDepthwiseF32Golden[];
constexpr unsigned int kDepthwiseF32GoldenSize = 256;

extern const unsigned char kDepthwiseDm2F32ModelData[];
extern const unsigned int kDepthwiseDm2F32ModelDataSize;
extern const float kDepthwiseDm2F32Input[];
constexpr unsigned int kDepthwiseDm2F32InputSize = 128;
extern const float kDepthwiseDm2F32Golden[];
constexpr unsigned int kDepthwiseDm2F32GoldenSize = 256;

#endif  // TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_MODEL_HARD_SWISH_DEPTHWISE_DATA_H_
