/* Copyright 2026 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Generated by gen_split_v_float.py using ai-edge-litert 2.2.0.
#ifndef TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SPLIT_V_FLOAT_GOLDENS_H_
#define TENSORFLOW_LITE_MICRO_KERNELS_HELIA_TESTS_SPLIT_V_FLOAT_GOLDENS_H_
#include <cstdint>
namespace {
constexpr int kSplitVInferredFloatShapes[][3] = {
    {2, 1, 3}, {2, 2, 3}, {2, 2, 3}};
constexpr int kSplitVInferredFloatCounts[] = {6, 12, 12};
constexpr uint32_t kSplitVInferredFloatGolden[] = {
    0x3f00f778, 0x3f011667, 0x3f013556, 0x3f02c779, 0x3f02e668, 0x3f030557,
    0x3f015445, 0x3f017334, 0x3f019223, 0x3f01b112, 0x3f01d001, 0x3f01eef0,
    0x3f032446, 0x3f034335, 0x3f036224, 0x3f038113, 0x3f03a002, 0x3f03bef1,
    0x3f020ddf, 0x3f022cce, 0x3f024bbd, 0x3f026aac, 0x3f02899b, 0x3f02a88a,
    0x3f03dde0, 0x3f03fccf, 0x3f041bbe, 0x3f043aad, 0x3f04599c, 0x3f04788b};
constexpr int kSplitVInferredInt32Shapes[][3] = {
    {2, 1, 3}, {2, 2, 3}, {2, 2, 3}};
constexpr int kSplitVInferredInt32Counts[] = {6, 12, 12};
constexpr uint32_t kSplitVInferredInt32Golden[] = {
    0xfffe2fff, 0xfffe4eee, 0xfffe6ddd, 0x00000000, 0x00001eef, 0x00003dde,
    0xfffe8ccc, 0xfffeabbb, 0xfffecaaa, 0xfffee999, 0xffff0888, 0xffff2777,
    0x00005ccd, 0x00007bbc, 0x00009aab, 0x0000b99a, 0x0000d889, 0x0000f778,
    0xffff4666, 0xffff6555, 0xffff8444, 0xffffa333, 0xffffc222, 0xffffe111,
    0x00011667, 0x00013556, 0x00015445, 0x00017334, 0x00019223, 0x0001b112};
constexpr int kSplitVMixedZeroFloatShapes[][3] = {
    {2, 0, 3}, {2, 2, 3}, {2, 0, 3}, {2, 3, 3}, {2, 0, 3}};
constexpr int kSplitVMixedZeroFloatCounts[] = {0, 12, 0, 18, 0};
constexpr uint32_t kSplitVMixedZeroFloatGolden[] = {
    0x3f00f778, 0x3f011667, 0x3f013556, 0x3f015445, 0x3f017334, 0x3f019223,
    0x3f02c779, 0x3f02e668, 0x3f030557, 0x3f032446, 0x3f034335, 0x3f036224,
    0x3f01b112, 0x3f01d001, 0x3f01eef0, 0x3f020ddf, 0x3f022cce, 0x3f024bbd,
    0x3f026aac, 0x3f02899b, 0x3f02a88a, 0x3f038113, 0x3f03a002, 0x3f03bef1,
    0x3f03dde0, 0x3f03fccf, 0x3f041bbe, 0x3f043aad, 0x3f04599c, 0x3f04788b};
constexpr int kSplitVMixedZeroInt32Shapes[][3] = {
    {2, 0, 3}, {2, 2, 3}, {2, 0, 3}, {2, 3, 3}, {2, 0, 3}};
constexpr int kSplitVMixedZeroInt32Counts[] = {0, 12, 0, 18, 0};
constexpr uint32_t kSplitVMixedZeroInt32Golden[] = {
    0xfffe2fff, 0xfffe4eee, 0xfffe6ddd, 0xfffe8ccc, 0xfffeabbb, 0xfffecaaa,
    0x00000000, 0x00001eef, 0x00003dde, 0x00005ccd, 0x00007bbc, 0x00009aab,
    0xfffee999, 0xffff0888, 0xffff2777, 0xffff4666, 0xffff6555, 0xffff8444,
    0xffffa333, 0xffffc222, 0xffffe111, 0x0000b99a, 0x0000d889, 0x0000f778,
    0x00011667, 0x00013556, 0x00015445, 0x00017334, 0x00019223, 0x0001b112};
constexpr int kSplitVTotalEmptyFloatShapes[][3] = {
    {2, 1, 0}, {2, 2, 0}, {2, 2, 0}};
constexpr int kSplitVTotalEmptyFloatCounts[] = {0, 0, 0};
constexpr uint32_t kSplitVTotalEmptyFloatGolden[] = {0x00000000};
constexpr int kSplitVTotalEmptyInt32Shapes[][3] = {
    {2, 1, 0}, {2, 2, 0}, {2, 2, 0}};
constexpr int kSplitVTotalEmptyInt32Counts[] = {0, 0, 0};
constexpr uint32_t kSplitVTotalEmptyInt32Golden[] = {0x00000000};
}  // namespace
#endif
