name: Ambiq Presubmit
#testing this out
on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
    secrets:
      NS_CMSIS_NN_SSH_KEY:
        required: true

jobs:
  ambiq_postmerge:
    runs-on: ubuntu-latest-md

    name: ambiq_unit_tests
    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.trigger-sha }}

      # Restore cache
      - name: Cache third-party downloads
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles('tensorflow/lite/micro/tools/make/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-third-party-downloads-

      - name: Run Cortex-M55 tests
        uses: docker://ghcr.io/ambiqai/ns-tflm-ci:latest
        env:
          NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
        with:
          args: /bin/sh -c tensorflow/lite/micro/tools/ci_build/test_ambiq_cortex_m55.sh

        # Run Cortex-M4 tests
      - name: Run Cortex-M4 tests
        uses: docker://ghcr.io/ambiqai/ns-tflm-ci:latest
        env:
          NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
        with:
          args: /bin/sh -c "tensorflow/lite/micro/tools/ci_build/test_ambiq_cortex_m4.sh"

      # Save cache
      - name: Save third-party downloads cache
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles('tensorflow/lite/micro/tools/make/Makefile') }}
