name: Ambiq Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest-md
    container:
      image: ghcr.io/ambiqai/ns-tflm-ci:latest
    env:
      tag: ${{ github.ref_name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure Git safe directory
        run: git config --global --add safe.directory '*'

      - name: Create artifacts
        run: |
          touch empty_file
          zip ../ns-tflm-$tag.zip empty_file
          tar -czf ../ns-tflm-$tag.tar.gz empty_file
          # bash ./neuralspot/build.sh
          # cd ${GITHUB_WORKSPACE}/build
          # Create neuralSPOT module
          # zip -r ../ns-tflm-$tag.zip *
          # tar -czf ../ns-tflm-$tag.tar.gz *
          # Create a snapshot of the repository
          git archive --format zip    --output repo-snapshot-$tag.zip HEAD
          git archive --format tar.gz --output repo-snapshot-$tag.tar.gz HEAD
          # Place files into artifacts directory
          mkdir -p ./artifacts
          mv ns-tflm-$tag.zip \
            ns-tflm-$tag.tar.gz \
            repo-snapshot-$tag.zip \
            repo-snapshot-$tag.tar.gz \
            ./artifacts

      - name: Create snapshot archives
        run: |

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: ./artifacts

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      tag: ${{ github.ref_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./artifacts
          gh release create "$tag" \
            ns-tflm-$tag.zip \
            ns-tflm-$tag.zip \
            ns-tflm-$tag.tar.gz \
            repo-snapshot-$tag.zip \
            repo-snapshot-$tag.tar.gz \
            -R "$GITHUB_REPOSITORY" \
            -t "Release $tag" \
            --notes "Automated release for tag $tag"
