name: Ambiq Unit Tests

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
    secrets:
      NS_CMSIS_NN_SSH_KEY:
        required: true

jobs:
  ambiq_test:
    runs-on: ubuntu-latest-md
    name: ambiq_unit_tests
    container:
      image: ghcr.io/ambiqai/helia-rt-ci:latest

    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.trigger-sha }}

      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "*"

      - name: Cache third-party downloads
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles(
            'tensorflow/lite/micro/tools/make/Makefile',
            'tensorflow/lite/micro/tools/make/third_party_downloads.inc'
            ) }}
          restore-keys: |
            ${{ runner.os }}-third-party-downloads-

      - name: Run Cortex-M55 tests
        env:
          NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
        run: /bin/sh -c "tensorflow/lite/micro/tools/ci_build/test_ambiq_cm4_cm55.sh cortex-m55 gcc"

      - name: Run Cortex-M4 tests
        env:
          NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
        run: /bin/sh -c "tensorflow/lite/micro/tools/ci_build/test_ambiq_cm4_cm55.sh cortex-m4+fp gcc"

      - name: Save third-party downloads cache
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles(
            'tensorflow/lite/micro/tools/make/Makefile',
            'tensorflow/lite/micro/tools/make/third_party_downloads.inc'
            ) }}
