name: Ambiq Presubmit

on:
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string

jobs:
  ambiq_presubmit:
    runs-on: ubuntu-latest-md

    name: ambiq_unit_tests
    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.trigger-sha }}

      # Restore cache
      - name: Cache third-party downloads
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles('tensorflow/lite/micro/tools/make/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-third-party-downloads-

      - name: Test
        uses: docker://ghcr.io/ambiqai/ns-tflm-ci:latest
        with:
          args: /bin/sh -c tensorflow/lite/micro/tools/ci_build/test_ambiq_corstone_300.sh

      # Save cache
      - name: Save third-party downloads cache
        uses: actions/cache@v3
        with:
          path: |
            tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles('tensorflow/lite/micro/tools/make/Makefile') }}
