name: heliaRT Unit Tests

on:

  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string
    secrets:
      NS_CMSIS_NN_SSH_KEY:
        required: true
      ARM_UBL_LICENSE_IDENTIFIER:
        required: false

  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build (branch, tag, or SHA). Leave empty to use the current commit."
        required: false
        default: ""

jobs:
  helia_test:
    runs-on: ubuntu-latest-md
    container:
      image: ghcr.io/ambiqai/helia-rt-ci:latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        arch: [ "cortex-m55", "cortex-m4+fp", "cortex-m3" ]
        toolchain: [ "gcc" ]

    env:
      NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
      ARM_UBL_LICENSE_IDENTIFIER: ${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }}

    name: test-${{ matrix.arch }}-${{ matrix.toolchain }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.trigger-sha }}

      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "*"

      - name: Cache third-party downloads
        uses: actions/cache@v3
        with:
          path: tensorflow/lite/micro/tools/make/downloads
          key: ${{ runner.os }}-third-party-downloads-${{ hashFiles('tensorflow/lite/micro/tools/make/Makefile','tensorflow/lite/micro/tools/make/third_party_downloads.inc') }}
          restore-keys: ${{ runner.os }}-third-party-downloads-

      - name: Testing (${{ matrix.arch }} / ${{ matrix.toolchain }})
        run: |
          /bin/sh -c "tensorflow/lite/micro/tools/ci_build/test_helia.sh \
          -a ${{ matrix.arch }} -t ${{ matrix.toolchain }}"
