name: Run-Ambiq

on:
  workflow_dispatch:

jobs:
  call-ambiq-build:
    if: ${{ github.repository == 'AmbiqAI/helia-rt' }}
    uses: ./.github/workflows/ambiq_build.yml
    with:
      trigger-sha: ${{ github.sha }}
    secrets:
      NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
      ARM_UBL_LICENSE_IDENTIFIER: ${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }}

  call-ambiq-test:
    if: ${{ github.repository == 'AmbiqAI/helia-rt' }}
    uses: ./.github/workflows/ambiq_test.yml
    with:
      trigger-sha: ${{ github.sha }}
    secrets:
      NS_CMSIS_NN_SSH_KEY: ${{ secrets.NS_CMSIS_NN_SSH_KEY }}
      ARM_UBL_LICENSE_IDENTIFIER: ${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }}

  issue-on-error:
    needs: [call-ambiq-build, call-ambiq-test]
    if: ${{ always() && (needs.call-ambiq-build.result == 'failure' || needs.call-ambiq-test.result == 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
      flag_label: ci:bot_issue
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
