name: Run-Ambiq

# This is the entry point for ambiq.yml for scheduled and workflow_dispatch events.

on:
  # Allow manually triggering of the workflow.
  workflow_call:
      inputs:
        trigger-sha:
          description: "SHA of the commit to test"
          required: true
          type: string

jobs:
  call-ambiq-presubmit:
    runs-on: ubuntu-latest-md
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.trigger-sha }}
      - name: Run Ambiq Presubmit
        uses: ./.github/workflows/ambiq_presubmit.yml
